export const tools = [
    "Twitter (X) Bio Generator",
    "Instagram Bio Generator",
    "Facebook Bio Generator",
    "LinkedIn Headline Generator",
    "TikTok Bio Generator",
    "Linkedin Company Headline Generator",
    "Threads Bio Generator",
    "LinkedIn Summary Generator",
    "LinkedIn Company Summary Generator",
    "YouTube Post Title Generator",
    "YouTube Post Description Generator",
    "Facebook Page Description Generator",
    "Instagram Caption Generator",
    "X (Twitter) Viral Post Generator",
    "X (Twitter) Threads Generator",
    "Facebook Post Caption Generator",
    "Facebook Group Post Generator",
    "Instagram Story Caption Generator",
    "Instagram Reel Caption Generator",
    "Paraphrase Tool",
    "Image Generator",
    "Email Generator",
    "Sales Email Generator",
    "Customer Service Email Generator",
    "Marketing Email Generator",
    "Product Email Generator",
    "HR Email Generator",
    "IT Email Generator",
    "Freestyle Email Generator",
    "Blog Ideas Generator",
    "Blog Titles Generator",
    "Blog Outline Generator",
    "Blog Post Generator",
    "Blog Intro Generator",
    "Web Page FAQ's Generator",
    "Website Hero Copy Generator",
    "Facebook Ad Headline Generator",
    "Website Testimonials Generator",
    "Google Ads Headline Generator",
    "Google Ad Description Generator",
    "Newsletter Generator",
    "Press Release Generator",
    "Article Generator",
    "Article Ideas Generator",
    "Article Outline Generator",
    "Article Intro Generator",
    "SEO Title & Description Generator",
    "Resume Generator",
    "Review Reply Generator",
    "Prompt Generator",
    "Post Hashtags Generator",
    "Threads Post Caption Generator",
    "Instagram Post Caption Generator",
    "Facebook Group Description Generator",
    "Audio to Text Conversion",
    "Text to Audio Conversion",
    "Language Translator Tool",
    "Video Script Generator",
    "Create Product Description",
    "Create Marketing Plan",
    "Create Marketing Funnel",
    "E-Mail Reply",
    "Excel-Sheet Expert",
    "Concept Clarifier",
    "Pros & Cons Tool🎯",
    "SEO Keyword Research",
    "Image Resizer",
    "Code Converter",
    "Marketing Strategy Campaign",
    "QR Code Generator",
    "Facebook Image Resizer",
    "Instagram Image Resizer",
    "Linkedin Image Resizer",
    "Pinterest Image Resizer",
    "Snapchat Image Resizer",
    "Twitter Image Resizer",
    "Youtube Image Resizer",
    "Web Component Generator",
    "Humanize AI Text",
    "Image to Text Converter",
    "JPG to PDF Converter",
    "PDF Merger",
    "PNG TO PDF Converter",
    "Youtube Video Downloader",
    "Youtube Audio Downloader",
    "Instagram Video Downloader",
    "Video to Audio Converter",
    "Instagram Post Downloader",
    "Facebook Video Downloader",
    "PNG To JPG Converter",
    "JPG To PNG Converter",
    "Tiktok Video Downloader",
    "TEXT To PDF Converter",
    "Twitter Video Downloader",
    "Podcast Generator",
    "JPG to SVG converter",
    "Files to Zip Converter",
    "Video to GIF Converter",
    "Text Summarizer",
    "Zip Extractor",
    "Speech to Image",
    "Quick Notes Generator",
    "PDF to Text Converter",
    "Compress Video",
    "Extract Images from PDF",
    "Domain Name Generator",
    "Business Name Generator",
    "PDF Translator",
    "Video to Text Converter",
    "Current Topic Generator",
    "Video Snip Expert",
    "Audio Snip Expert",
    "PDF Page Snip Tool",
    "NDA Generator",
    "YouTube Script Generator",
    "NCA Generator",
    "Business Slogan Generator",
    "Content Improver",
    "Trivia Generator",
    "Remove Audio from Video",
    "Poll Generator",
    "Privacy Policy Generator",
    "Business Plan Generator",
    "Audio Video Combiner",
    "PDF Summarizer Tool",
    "PDF Q&A Tool",
    "Audio Translation Tool",
    "Video to Audio Translation Tool",
    "Video Translation Tool",
    "YouTube Translation Tool",
    "Finance Advisor Tool",
    "Crop Image Tool",
    "AI Detector Tool",
    "News Summarizer Tool",
    "Text Infographic Tool",
    "Image Compressor Tool",
    "Avatar Generator Tool",
    "SWOT Analysis Generator Tool",
    "Cover Letter Generator Tool",
    "Logo Generator Tool"
  ];